extends Node
## Sfx autoload — one-line access to the synthetic SFX set.
##
## All streams come from assets/audio/sfx/ (generated by
## tools/gen_sfx_wavs.py — license-clean, swappable for CC0 recordings
## later without touching call sites). One-shots play through a small pool
## of reusable AudioStreamPlayer3D nodes with random pitch jitter so
## repeated hits never sound machine-gunned; loops get dedicated players
## attached to their owner (fire, river) or the mixer (rain bed).

const SFX_DIR := "res://assets/audio/sfx/"
const POOL_SIZE := 16

var _streams: Dictionary = {}
var _pool: Array[AudioStreamPlayer3D] = []
var _pool_idx: int = 0
## Shutdown gate: once true, no new playback may start. Set by the combat
## test harness right before quitting — any stream still playing (or started
## in the quit grace frames) keeps its AudioStreamPlayback alive inside the
## AudioServer and shows up as "ObjectDB instances leaked at exit" in every
## headless run. The harness sweeps existing players; this stops new ones.
var muted: bool = false


func _ready() -> void:
	for i in range(POOL_SIZE):
		var p := AudioStreamPlayer3D.new()
		p.name = "OneShot%d" % i
		p.max_distance = 60.0
		p.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_DISTANCE
		add_child(p)
		_pool.append(p)


func _get_stream(sfx_name: String, looped: bool = false) -> AudioStream:
	if _streams.has(sfx_name):
		return _streams[sfx_name]
	var path := SFX_DIR + sfx_name + ".wav"
	if not ResourceLoader.exists(path):
		push_warning("Sfx: missing stream '%s'" % path)
		_streams[sfx_name] = null
		return null
	var stream: AudioStream = load(path)
	if looped and stream is AudioStreamWAV:
		var wav := stream as AudioStreamWAV
		wav.loop_mode = AudioStreamWAV.LOOP_FORWARD
		wav.loop_begin = 0
		wav.loop_end = wav.data.size() / 2  # frames (16-bit mono)
	_streams[sfx_name] = stream
	return stream


## Positional one-shot. Pitch jitter keeps repeats organic.
func play3d(sfx_name: String, pos: Vector3, volume_db: float = 0.0,
		pitch_jitter: float = 0.08) -> void:
	if muted:
		return
	var stream := _get_stream(sfx_name)
	if stream == null:
		return
	var p := _pool[_pool_idx]
	_pool_idx = (_pool_idx + 1) % POOL_SIZE
	p.stop()
	p.stream = stream
	p.global_position = pos
	p.volume_db = volume_db
	p.pitch_scale = 1.0 + randf_range(-pitch_jitter, pitch_jitter)
	p.play()


## Looping spatial emitter attached to `parent` (fire crackle, river).
## Freed with its parent; returns the player for volume control.
func loop3d(sfx_name: String, parent: Node, offset: Vector3 = Vector3.ZERO,
		volume_db: float = 0.0, max_dist: float = 30.0) -> AudioStreamPlayer3D:
	if muted:
		return null
	var stream := _get_stream(sfx_name, true)
	if stream == null:
		return null
	var p := AudioStreamPlayer3D.new()
	p.name = "Loop_" + sfx_name
	p.stream = stream
	p.volume_db = volume_db
	p.max_distance = max_dist
	p.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_DISTANCE
	p.position = offset
	p.autoplay = true
	parent.add_child(p)
	p.play()
	return p


## Non-positional loop (ambience beds). Returns the player.
func loop2d(sfx_name: String, volume_db: float = -18.0) -> AudioStreamPlayer:
	if muted:
		return null
	var stream := _get_stream(sfx_name, true)
	if stream == null:
		return null
	var p := AudioStreamPlayer.new()
	p.name = "Bed_" + sfx_name
	p.stream = stream
	p.volume_db = volume_db
	add_child(p)
	p.play()
	return p
